import { useState, useEffect } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Video from 'src/components/Video';
import WrapVideo from 'src/components/WrapVideo';

const Home: NextPage = () => {
  const [position, setPosition] = useState(0);
  useEffect(() => {
    const time = setInterval(() => {
      console.log('aqui...');
      setPosition((oldPosition) => oldPosition + 1);
    }, 500);

    return () => {
      clearInterval(time);
    }
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={
          {
            width: '100%',
            minWidth: '300px'
          }
        }
      >
        <WrapVideo />
      </div>
      <br />
      <br />
      <br />
      <br />
      <div
        style={
          {
            width: '200px',
          }
        }
      >
      <WrapVideo />
      </div>
    </>
  )
}

export default Home
