import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import useTranslation from "next-translate/useTranslation";
import { withUnleash } from "next-unleash";
import { Media } from "src/components/Media";

const Home: NextPage = ({ toggles }: any) => {
  const { t } = useTranslation("common");
  const { t: th } = useTranslation("home");
  const { locale } = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          width: "100%",
          minWidth: "200px",
        }}
      >
        <Media
          src="https://iandevlin.github.io/mdn/video-player-with-captions/video/sintel-short.mp4"
          type="video/mp4"
        />
      </div>
      Locale: {locale}
      Translation: {t("title")}
      Translation: {th("title")}
      {console.log("asdf", toggles.toggleTeste1)}
      <br />
      <br />
      <br />
      <br />
      <div
        style={{
          width: "200px",
        }}
      />
    </>
  );
};

export default withUnleash(Home);
