import type { NextPage } from "next";
import Head from "next/head";
import { Media } from "src/components/Media";

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div
      style={{
        width: "100%",
        minWidth: "200px",
      }}
    >
      <Media
        src="https://iandevlin.github.io/mdn/video-player-with-captions/video/sintel-short.mp4"
        type="video/mp4"
      />
    </div>
    <br />
    <br />
    <br />
    <br />
    <div
      style={{
        width: "200px",
      }}
    />
  </>
);

export default Home;
